badges:
  type: list
  default: ""
  description:
    en: 'Use the name of the badge as it appears on the
      <a href="/admin/badges">list of badges</a>.
      Post badges will appear in the order they are
      added to this setting.'
badge_link_destination:
  type: enum
  default: "user's badge page"
  choices:
    - "badge overview page"
  description:
    en: "Where a user will be taken when they click on a post badge."
only_show_highest_trust_level:
  type: bool
  default: false
  description:
    en: "When including trust level badges (Basic, Member, Regular, Leader),
      only show the highest trust level a user has earned."
